### ISSUE TITLE
void

### ISSUE THREAD

**Issue by abebeos** [bitfocus/companion-module-bitfocus-companion#51]

**Comment by abebeos** [comment]
I would do anyways only the trivial parts to get in contact with the code, e.g. identical option-field definitions, like:

```js
{
type: 'dropdown',
label: 'Bank',
tooltip: 'Which Button?',
id: 'bank',
default: '0',
choices: self.CHOICES_BANKS,
}				},
```

becomes a reusable

```js
self.FIELD_BANK = {
{
type: 'dropdown',
label: 'Bank',
tooltip: 'Which Button?',
id: 'bank',
default: '0',
choices: self.CHOICES_BANKS,
}	
}
```

This should make your later rewrite easier.

**Comment by abebeos** [comment]
> as all the `system.emit` and `system.on` calls will need to be removed and replaced with methods that are not exposed to the modules

Could you describe why the (EventEmitter) based CompanionSystem object is to be replaced with an alternative solution? Hiding functionality from modules does not feel like a valid reason for a full replacement.

(The overall EventEmiiter seems highly flexible, and decently implemented within companion)

**Comment by krocheck** [comment]
> Could you describe why the (EventEmitter) based CompanionSystem object is to be replaced with an alternative solution? Hiding functionality from modules does not feel like a valid reason for a full replacement.
> 
> (The overall EventEmiiter seems highly flexible, and decently implemented within companion)

As I've stated before, security of the core is a major imperative.  Modules can literally hook anything in the core at this time and that's fine while we're reviewing all the modules but in that future world where modules can be brought in and update out-of-band, that can lead to modules that do surreptitious things that we didn't approve of or intend to allow.  We want modules to have an explicit set of API calls and if they need something that isn't present we'll find an appropriate way to add that, if possible.  A module could literally write a loop and reset every button just because.  That's not good architecture!

A second major flaw is that the events architecture is not tight.  I simply mean that when you have one-to-many events that the execution order is not explicit and if you look closely there's a lot of hacks in the system to help that fact that there's a bunch of asynchronous event flying around

Third major flaw is that there are inline events that basically expect synchronous execution, and that is fundamentally flawed for this type of architecture.   Take [this before](https://github.com/bitfocus/companion/blob/25a303b7adbf1a2a77f6bcef448d17e1fb7d50d9/lib/loadsave.js#L801-L803) and [this after](https://github.com/bitfocus/companion/blob/3d6e6f3660d17a9c6c5e40f91360d79615c3eab9/lib/Data/ImportExport.js#L204) being converted to a structured API.  (the class I linked to hasn't been fully converted yet, but its calls to other classes that have been updated were swapped out)  The simple fact is its cleaner, the structure is easier to read, its a properly synchronous call in a synchronous function, and we're actually saving a number of CPU cycles by not registering the event and then letting it fire.  Sure, the CPU load is not a massive decrease given the capabilities of modern processors, but it still makes a more efficient and streamlined execution.

And to be clear, modules will still effectively use the `system` events architecture, its just that only modules and a couple edge cases on the core itself will continue to use that.  That's the security aspect ... we make it so its not possible for modules to get at what they shouldn't have.

**Comment by Julusian** [comment]
> (The overall EventEmiiter seems highly flexible, and decently implemented within companion)

Yes, its too flexible. Everything that modules are doing with `system.on` and `system.emit` are internal apis. I have at least twice broken functionality in a bunch of modules because they were using events that I wasnt expecting them to. As we want a stable module api, its going to either be incredibly messy and a lot of work to maintain internal apis throughout reworking of various stuff, or modules will break at random points. That wont make companion feel like stable software.
For me, this is one of the biggest reasons for moving away from system and for locking down the api.
It's not too bad today, but I do have to remember to check for modules using any of the events that I changed/removed, but once we allow users to add in 3rd party modules, we can't fix those and will struggle to provide any hinting about whether it should work.

But yes, I would say application integrity rather than security. We cant expect this to be 100% secure, because modules will still be able to do file io and stuff, so there are ways around any barriers, but if modules have free reign to play with our internal data structures and stuff then they will have plenty of opportunity to break things either maliciously or accidentally.

The architecture makes it really hard to understand the flow of anything. Intellisense or similar ide technologies are no help in this codebase because of the events. While for some of the uses events are appropriate, but most of them are using events as method calls, so events adds confusion. 
Do you know the difference between these two events? https://github.com/bitfocus/companion/blob/master/lib/feedback.js#L259-L261 You can find out by searching the code, or remember from getting it wrong in the past.

> Third major flaw is that there are inline events that basically expect synchronous execution

Yes, the way we assume that the events will execute synchronously is an ugly hack. I am rather surprised that this hasnt caused more issues already, I am pretty sure there are no guarantees made by the EventEmitter to execute the handler synchronously

> And to be clear, modules will still effectively use the system events architecture, its just that only modules and a couple edge cases on the core itself will continue to use that. 

@krocheck Will we? I was intending to not provide anything system like to the modules. Other than the socket.io client they have now (which I guess is kinda similar)

**Comment by krocheck** [comment]
> @krocheck Will we? I was intending to not provide anything system like to the modules. Other than the socket.io client they have now (which I guess is kinda similar)

Yeah "effectively" I was referring to the new `socket.io` interface.

**Comment by abebeos** [comment]
> > Could you describe why the (EventEmitter) based CompanionSystem object is to be replaced with an alternative solution? Hiding functionality from modules does not feel like a valid reason for a full replacement.
> > (The overall EventEmiiter seems highly flexible, and decently implemented within companion)

(thank you for the thorough elaborations, I'll just extract some points without further comment, as I'm close to an "overload")
 
> As I've stated before, security of the core is a major imperative. Modules can literally hook anything in the core at this time and that's fine while we're reviewing all the modules but in that future world where modules can be brought in and update out-of-band, that can lead to modules that do surreptitious things that we didn't approve of or intend to allow. We want modules to have an explicit set of API calls and if they need something that isn't present we'll find an appropriate way to add that, if possible. A module could literally write a loop and reset every button just because. That's not good architecture!

### => Restrict User Modules Access to Core Functionality

 
> A second major flaw is that the events architecture is not tight. I simply mean that when you have one-to-many events that the execution order is not explicit and if you look closely there's a lot of hacks in the system to help that fact that there's a bunch of asynchronous events flying around

### => Ordered Execution of Multi-Subscriber Events
 
> Third major flaw is that there are inline events that basically expect synchronous execution, and that is fundamentally flawed for this type of architecture. Take [this before](https://github.com/bitfocus/companion/blob/25a303b7adbf1a2a77f6bcef448d17e1fb7d50d9/lib/loadsave.js#L801-L803) and [this after](https://github.com/bitfocus/companion/blob/3d6e6f3660d17a9c6c5e40f91360d79615c3eab9/lib/Data/ImportExport.js#L204) being converted to a structured API. (the class I linked to hasn't been fully converted yet, but its calls to other classes that have been updated were swapped out) The simple fact is its cleaner, the structure is easier to read, its a properly synchronous call in a synchronous function, and we're actually saving a number of CPU cycles by not registering the event and then letting it fire. Sure, the CPU load is not a massively decreased given the capabilities of modern processors, but it still makes a more efficient and streamlined execution.

### => Avoid Unnecessary Asynchronicity


> And to be clear, modules will still effectively use the `system` events architecture, its just that only modules and a couple edge cases on the core itself will continue to use that. That's the security aspect ... we make it so its not possible for modules to get at what they shouldn't have.

### => Limit Use of Asynchronous Event System

**Comment by abebeos** [comment]
> > (The overall EventEmiiter seems highly flexible, and decently implemented within companion)


(same as above: thank you for the thorough elaborations, I'll just extract some points without further comment, as I'm close to an "overload")

> Yes, its too flexible. Everything that modules are doing with `system.on` and `system.emit` are internal apis. I have at least twice broken functionality in a bunch of modules because they were using events that I wasnt expecting them to. As we want a stable module api, its going to either be incredibly messy and a lot of work to maintain internal apis throughout reworking of various stuff, or modules will break at random points. That wont make companion feel like stable software. For me, this is one of the biggest reasons for moving away from system and for locking down the api. It's not too bad today, but I do have to remember to check for modules using any of the events that I changed/removed, but once we allow users to add in 3rd party modules, we can't fix those and will struggle to provide any hinting about whether it should work.

=> Provide/Document the Stable API
 
> But yes, I would say application integrity rather than security. We cant expect this to be 100% secure, because modules will still be able to do file io and stuff, so there are ways around any barriers, but if modules have free reign to play with our internal data structures and stuff then they will have plenty of opportunity to break things either maliciously or accidentally.

=> Ensure Core Data Encapsulation
 
> The architecture makes it really hard to understand the flow of anything. Intellisense or similar ide technologies are no help in this codebase because of the events. While for some of the uses events are appropriate, but most of them are using events as method calls, so events adds confusion. Do you know the difference between these two events? https://github.com/bitfocus/companion/blob/master/lib/feedback.js#L259-L261 You can find out by searching the code, or remember from getting it wrong in the past.

=> Ensure IDE Intellisense work Fine
 
> > Third major flaw is that there are inline events that basically expect synchronous execution
> 
> Yes, the way we assume that the events will execute synchronously is an ugly hack. I am rather surprised that this hasnt caused more issues already, I am pretty sure there are no guarantees made by the EventEmitter to execute the handler synchronously

=> Provide Construct for Synchronous Executions of Asynchronous Events
 
> > And to be clear, modules will still effectively use the system events architecture, its just that only modules and a couple edge cases on the core itself will continue to use that.
> 
> @krocheck Will we? I was intending to not provide anything system like to the modules. Other than the socket.io client they have now (which I guess is kinda similar)

=> Avoid Architectural Overuse of EventEmitter

**Comment by abebeos** [comment]
Ok, I'm good for now. The information is enough to understand the need to reduce the use of events significantly and to produce the relevant documentation

So, at this point, I agree fully with 

* the need to reduce EventEmitter usage, significantly

I disagree with the "full redesign" approach.

I still believe that this can be achieved without a major redesign (e.g. keep the original code structure more or less intact). This is what https://github.com/abebeos/companion/issues/1 is about.

But even if I manage to convince some people for [this](https://github.com/abebeos/companion/issues/1), I could not execute it without the consensus of the core-devs, as I would depend in several cases on their domain-knowledge (and in some rare cases their coding-experience). And naturally on "refactoring steps being merged fast". Otherwise I would need potentially twice the amount of time, or even more.

So, @krocheck & @Julusian , what do you think? What you be ok with me doing a parallel attempt towards a modernized companion, but using refactoring techniques (how I do it: don't know, that's a dynamic process)?

**Comment by krocheck** [comment]
I don't think I understand what a "modernized companion" is that you'd be working on compared to the work in being done in `develop`.

**Comment by abebeos** [comment]
The main difference is in the process ("Processing: Use strict refactoring first, Achieve small, non-breaking and mergeable changes"), and in the final result (to "keep the original code structure more or less intact").

So, I would try to fix any (by-design, by-architecture )problems, with the minimum possible changes to the code. And if I apply changes, those would be non-critical non-breaking refactoring steps, or slight-breaking rework-steps.

(chances are there that I fail, and/or that I've assessed all this wrong. But I'm 98% sure it's doable)

**Comment by krocheck** [comment]
> fix any (by-design, by-architecture )problems

We would need to review what these are because I think it would be a case-by-case basis whether its worth your time to pursue.

But we don't have a space for you to dev/test these with CI to get them to the public.  Our branches are:

1. `master` current stable build
2. `beta` module work and core bug fixes for current stable (effectively release staging/testing)
3. `develop` next major/minor release

We really don't need yet another development branch to manage.

**Comment by abebeos** [comment]
I'm asking you very(!) generally here, to avoid investing more time in convincing other relevant people.

The technical project-details are "peanuts", nothing that cannot be solved. I guess I would be working against master (current 2.2.*), can be done even with usual PRs initially. Simple refactoring (like e.g. https://github.com/bitfocus/companion-module-bitfocus-companion/pull/52) could go directly into master I guess, more complex possibly indirectly via beta.

I would "stay out of your way", and would just need priority PR review, that would be enough for me at the beginning.
